# Generated by Django 6.0.4 on 2026-04-21 23:50

import CrosswordCreator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        default=CrosswordCreator.models.generate_unique_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rows", models.IntegerField(default=15)),
                ("cols", models.IntegerField(default=15)),
                ("grid", models.JSONField(default=list)),
                ("clues", models.JSONField(default=dict)),
            ],
        ),
    ]
